config/routes.rb
Rails.application.routes.draw do
  root to: "cats#index"
  resources :cats, only: %i[index show new create] do
    resources :reservations, only: %i[new]
    resources :reservations, only: %i[create], path: ''
  end
  namespace :admin do
    resources :cats, only: %i[index show]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :reservations, dependent: :destroy
  belongs_to :user
  validates :address, presence: true
  validates :gender, presence: true
  validates :breed, presence: true
  validates :price, presence: true
  validates :name, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  enum gender: { male: 'Male', female: 'Female' }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_breed,
    against: [ :name, :breed ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < ApplicationController
  def index
    @cats = Cat.all
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @cats = Cat.all
    if params[:query].present?
      sql_subquery = "name ILIKE :query OR breed ILIKE :query"
      @cats = @cats.where(sql_subquery, query: "%#{params[:query]}%")
    else
      @cats = Cat.all
    end
  end

  def show
    @cat = Cat.find(params[:id])
    @reservation = Reservation.new
    @marker = [{ lat: @cat.latitude, lng: @cat.longitude }]
    @disabled_dates = @cat.reservations.map do |a|
      {
        from: a.starting_date,
        to: a.ending_date
      }
    end

  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save!
      redirect_to admin_cats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :address, :gender, :breed, :price, :photo)
  end
end

app/views/admin/cats/index.html.erb
<div class="container my-cats-container">
  <div class="title-div-admin-index">
    <h1>All my cats</h1>
    <% if user_signed_in? %>
      <%= link_to 'Add a cat', new_cat_path, class: "orange-btn blue-btn" %>
      <% end %>
  </div>
  <div class="card-main">
    <% current_user.cats.each do |cat| %>
      <%= link_to cat_path(cat) do %>
      <div class="card-index">
        <%= cl_image_tag cat.photo.key %>
        <div class="card-index-infos">
          <div>
            <h2><%= cat.name %></h2>
            <p><%= cat.breed %></p>
          </div>
          <div class="card-index-right">
            <h2><i class="fa-solid fa-<%= cat.gender == "female" ? "venus" : "mars" %>" style="color: #DB8434;;"></i></h2>
            <p><%= cat.price %> € / d</p>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>