config/routes.rb
Rails.application.routes.draw do
  root to: "cats#index"
  resources :cats, only: %i[index show new create] do
    resources :reservations, only: %i[new]
    resources :reservations, only: %i[create], path: ''
  end
  namespace :admin do
    resources :cats, only: %i[index show]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :reservations, dependent: :destroy
  belongs_to :user
  validates :address, presence: true
  validates :gender, presence: true
  validates :breed, presence: true
  validates :price, presence: true
  validates :name, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  enum gender: { male: 'Male', female: 'Female' }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_breed,
    against: [ :name, :breed ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < ApplicationController
  def index
    @cats = Cat.all
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @cats = Cat.all
    if params[:query].present?
      sql_subquery = "name ILIKE :query OR breed ILIKE :query"
      @cats = @cats.where(sql_subquery, query: "%#{params[:query]}%")
    else
      @cats = Cat.all
    end
  end

  def show
    @cat = Cat.find(params[:id])
    @reservation = Reservation.new
    @marker = [{ lat: @cat.latitude, lng: @cat.longitude }]
    @disabled_dates = @cat.reservations.map do |a|
      {
        from: a.starting_date,
        to: a.ending_date
      }
    end

  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save!
      redirect_to admin_cats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :address, :gender, :breed, :price, :photo)
  end
end

app/views/cats/index.html.erb
<div class="title-div-index">
  <h1>Which cat do you like ?</h1>
</div>

<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: cats_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: " searchbar form-control rounded-pill mr-2 p-2",
            placeholder: "Search a cat by name or breed"
        %>
      <%= submit_tag "Search", name: "", class: "btn orange-btn rounded-pill" %>
    <% end %>
  </div>
 </div>

  <div class="card-main">
    <% @cats.each do |cat| %>
      <%= link_to cat_path(cat) do %>
      <div class="card-index">
        <%= cl_image_tag cat.photo.key %>
        <div class="card-index-infos">
          <div>
            <h2><%= cat.name %></h2>
            <p><%= cat.breed %></p>
          </div>
          <div class="card-index-right">
            <h2><i class="fa-solid fa-<%= cat.gender == "female" ? "venus" : "mars" %>" style="color: #DB8434;;"></i></h2>
            <p><%= cat.price %> € / d</p>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>

app/views/cats/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Tell us about your cat</h3>
        <%= simple_form_for @cat do |f| %>
          <%= f.input :name, placeholder: 'Your meow name' %>
          <%= f.input :address, placeholder: 'Bordeaux' %>
          <%= f.input :gender, collection: Cat.genders.keys, prompt: 'Select gender' %>
          <%= f.input :breed %>
          <%= f.input :price, input_html: { min: '0', step: 'any' }, placeholder: 'For a day' %>
          <%= f.file_field :photo %>
          <%= f.submit "Create Cat", class: 'green-btn', style: 'margin-top:10px;' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cats/show.html.erb
<div class="all">
  <div class="row1">
    <div id="picture">
      <%= cl_image_tag @cat.photo.key if @cat.photo.attached? %>
    </div>
    <div id="description">
      <h2><strong><%= @cat.name %> </strong><i class="fa-solid fa-<%= @cat.gender == "female" ? "venus" : "mars" %>" style="color: #DB8434;;"></i></h2>
      <h3><%= @cat.breed %></h3>
      <p>Discover our adorable feline, named <%= @cat.name %>! <%= @cat.name %> is a feline beauty with captivating eyes and silky fur. Her playful and curious nature makes her the perfect companion to brighten up your days. She loves to explore new corners and cuddle up by your side during quiet moments. With her natural elegance and playful spirit, <%= @cat.name %> perfectly embodies feline grace and the love that cats bring into our lives. She can't wait to meet you!</p>
      <p class="price"> <strong><%= @cat.price %>€ / day</strong></p>
    </div>
  </div>

  <div class="row2">
    <div id="map" data-controller="map" data-map-markers-value="<%= @marker.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <div id="booking">
      <%= simple_form_for @reservation, url: cat_reservations_path(@cat) do |f| %>
        <%= f.input :starting_date,
                    as: :string,
                    class: "your-custom-class",
                    input_html: {
                      data: {
                        controller: "datepicker",
                        datepicker_disabled_dates_value: @disabled_dates.to_json
                        }
                      },
                    label: "Add an availability" %>
        <% f.hidden_field  :ending_date, as: :date %>
        <%= f.button :submit, "Book #{@cat.name}", class: "green-btn", style: "float: right;" %>
      <% end %>
    </div>
  </div>
</div>
<div class="row2"<%= @cat.user.id == current_user.id ? '' : 'style=display:none;' %>>
  <div id="bookings">
    <h2>My Cat's Bookings</h2>
    <table style="border='1px solid black' ">
      <tr>
        <td>Users</td>
        <td>Starting day</td>
        <td>Ending day</td>
      </tr>
      <% @cat.reservations.each do |reservation| %>
        <tr>
          <td><%= User.find(reservation.user_id).name %></td>
          <td><%= reservation.starting_date %></td>
          <td><%= reservation.ending_date %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="comments">
  <h2>Comments</h2>
    <div>
      <p><span class="user-name"><strong>Emma</strong></span>
      <i class="fa-solid fa-star"></i>
      <i class="fa-solid fa-star"></i>
      <i class="fa-solid fa-star"></i>
      <i class="fa-solid fa-star"></i>
      <i class="fa-solid fa-star"></i></p>
      <p>Spending a day with <%= @cat.name %> was like an enchanted interlude. Her boundless energy and curiosity kept me entertained from morning till night. It was an incredible adventure, and I will never forget the joy of playing with her and watching her explore with so much enthusiasm. <%= @cat.name %>, you are a little shining star!</p>
    </div>
    <div>
      <p><span class="user-name"><strong>Elodie</strong></span>
      <i class="fa-solid fa-star"></i>
      <i class="fa-solid fa-star"></i>
      <i class="fa-solid fa-star"></i>
      <i class="fa-solid fa-star"></i>
      <i class="fa-regular fa-star"></i></p>
      <p>Three incredible days in the company of <%= @cat.name %>! She welcomed me into her world with warmth and joy. The moments of relaxing cuddles were just as precious as the lively play sessions. Each day with her was a new discovery, a new adventure. <%= @cat.name %>, you made these three days unforgettable.</p>
    </div>
  </div>
</div>