config/routes.rb
Rails.application.routes.draw do
  root to: "cats#index"
  resources :cats, only: %i[index show new create] do
    resources :reservations, only: %i[new]
    resources :reservations, only: %i[create], path: ''
  end
  namespace :admin do
    resources :cats, only: %i[index show]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav class="navbar navbar-light p-2 border-bottom border-gray" style="background-color: #FFDEBF;">
      <div class="d-flex align-items-center">
        <%= link_to cats_path do %>
          <img src="https://cdn4.iconfinder.com/data/icons/animals-177/512/Cat-512.png" width="50px" height="50px">
        <% end %>
        <%= link_to 'Catz', cats_path, id: "catz" %>
        </div>
        <div class="d-flex align-items-center ml-auto">
          <% if user_signed_in? %>
            <%= link_to 'See all my catz', admin_cats_path, class: "blue-btn" %>
          <% end %>
          <div class="px-2"></div>
          <div>
            <% if user_signed_in? %>
              <%= link_to 'Sign out', destroy_user_session_path, class: "orange-btn", data: { turbo_method: :delete } %>
            <% else %>
              <%= link_to 'Sign in / up', new_user_session_path, class: "orange-btn" %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
      <div class="container">
        <%= yield %>
      </div>
      <%= render partial: 'layouts/footer' %>
  </body>
</html>